// Types for src/content/resume.json, which is generated by the resume repo
// (`make json`) and refreshed here at build time by scripts/fetch-resume.ts.
//
// Do not edit the JSON by hand -- the next build overwrites it. Content changes
// belong in the resume repo's YAML, which is also what produces the PDF, so the
// two cannot disagree.

import data from './resume.json'

export type Link = { label: string; url: string }

export type Bullet = {
  text: string
  tags?: string[]
  priority?: number
}

export type Role = {
  company: string
  title: string
  subtitle?: string
  location?: string
  /** Preformatted by the generator, e.g. "Jun 2024 – Jul 2026". */
  dates: string
  /** Raw "YYYY-MM" or "present", kept so a consumer can sort without parsing `dates`. */
  start: string
  end: string
  bullets: Bullet[]
}

export type Resume = {
  variant: string
  profile: {
    name: string
    location: string
    email: string
    /** Rows of links; the PDF renders one row per inner list. */
    link_lines: Link[][]
    summary: string
  }
  experience: Role[]
  projects: {
    heading: string
    name: string
    meta?: string
    bullets: Bullet[]
  }
  skills: { groups: { label: string; text: string }[] }
  education: { entries: { degree: string; detail?: string }[] }
}

export const resume = data as Resume
